# Generated by Django 4.2.1 on 2023-05-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudioAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StudioAdmin.parameter'),
        ),
        migrations.AddField(
            model_name='quota',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StudioAdmin.product'),
        ),
        migrations.AlterUniqueTogether(
            name='quota',
            unique_together={('product', 'parameter')},
        ),
    ]
