# Generated by Django 4.2.1 on 2023-05-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioAdmin', '0002_quota_parameter_quota_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='value',
            field=models.IntegerField(db_column='COL_VALUE', default=0),
        ),
    ]
