# Generated by Django 4.2.1 on 2023-05-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudioAdmin', '0005_alter_feature_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='products',
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StudioAdmin.feature')),
                ('product', models.ForeignKey(db_column='COL_PRODUCT_ID', default=None, on_delete=django.db.models.deletion.CASCADE, to='StudioAdmin.product')),
            ],
            options={
                'db_table': 'T_PRODUCT_FEATURE',
                'unique_together': {('product', 'feature')},
            },
        ),
    ]
